# Generated by Django 4.2 on 2023-04-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('experiance', models.TextField()),
                ('skills', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
