# Generated by Django 4.2 on 2023-04-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employee_experiance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='join_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
